<template><div><p>思考题：数组转化成树(难点-难点-难点)</p>
<p>背景</p>
<p>后端接口返回的数据一般是平铺的数组结构，而不会是树形结构，例如下面的平铺数组结构：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>data <span class="token operator">=</span> 
<span class="token punctuation">[</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"01"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"张大大"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">""</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"项目经理"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"02"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小亮"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"01"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"产品leader"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"03"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小美"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"01"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"UIleader"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"04"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"老马"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"01"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"技术leader"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"05"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"老王"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"01"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"测试leader"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"06"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"老李"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"01"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"运维leader"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"07"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小丽"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"02"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"产品经理"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"08"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"大光"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"02"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"产品经理"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"09"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小高"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"03"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"UI设计师"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"10"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小刘"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"04"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"前端工程师"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"11"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小华"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"04"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"后端工程师"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"12"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小李"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"04"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"后端工程师"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"13"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小赵"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"05"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"测试工程师"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"14"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小强"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"05"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"测试工程师"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"15"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小涛"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"06"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"运维工程师"</span><span class="token punctuation">}</span>
<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这样的数据可以直接在table中使用，但是不能直接在tree组件中使用，需要我们做一些转换。</p>
<p>额外补充一个函数来做转换</p>
<p>代码</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>
<span class="token keyword">const</span> data <span class="token operator">=</span> <span class="token punctuation">[</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"01"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"张大大"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">""</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"项目经理"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"02"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小亮"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"01"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"产品leader"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"03"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小美"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"01"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"UIleader"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"04"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"老马"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"01"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"技术leader"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"05"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"老王"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"01"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"测试leader"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"06"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"老李"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"01"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"运维leader"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"07"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小丽"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"02"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"产品经理"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"08"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"大光"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"02"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"产品经理"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"09"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小高"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"03"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"UI设计师"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"10"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小刘"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"04"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"前端工程师"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"11"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小华"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"04"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"后端工程师"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"12"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小李"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"04"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"后端工程师"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"13"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小赵"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"05"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"测试工程师"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"14"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小强"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"05"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"测试工程师"</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">{</span><span class="token literal-property property">id</span><span class="token operator">:</span><span class="token string">"15"</span><span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> <span class="token string">"小涛"</span><span class="token punctuation">,</span> <span class="token literal-property property">pid</span><span class="token operator">:</span><span class="token string">"06"</span><span class="token punctuation">,</span> <span class="token literal-property property">job</span><span class="token operator">:</span> <span class="token string">"运维工程师"</span><span class="token punctuation">}</span>
<span class="token punctuation">]</span>

<span class="token comment">// 完成代码</span>
<span class="token comment">// 1. 有现成包 array-to-tree</span>
<span class="token comment">// 2. 百度 js 数组转成树 有一堆答案</span>
<span class="token keyword">function</span> <span class="token function">arrToTree</span><span class="token punctuation">(</span><span class="token parameter">data</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  
  <span class="token comment">// 你的代码</span>
  
<span class="token punctuation">}</span>

<span class="token comment">// 目标：</span>
<span class="token keyword">const</span> treeData <span class="token operator">=</span> <span class="token function">arrToTree</span><span class="token punctuation">(</span>data<span class="token punctuation">)</span>
<span class="token comment">// treeData就是：</span>
<span class="token comment">// [{</span>
<span class="token comment">//   label: '张大大',</span>
<span class="token comment">//   children: [</span>
<span class="token comment">//     {</span>
<span class="token comment">//       label: '小亮',</span>
<span class="token comment">//       children: [{label: '小丽'}，{label: '大光'}]</span>
<span class="token comment">//     },</span>
<span class="token comment">//     {</span>
<span class="token comment">//       label: '小美',</span>
<span class="token comment">//       children: [{label: '小高'}]</span>
<span class="token comment">//     },</span>
<span class="token comment">//     {</span>
<span class="token comment">//       label: '老马',</span>
<span class="token comment">//       children: [{label: '小刘'}，{label: '小华'},{label: '小李'}]</span>
<span class="token comment">//     },</span>
<span class="token comment">//     {</span>
<span class="token comment">//       label: '老王',</span>
<span class="token comment">//       children: [{label: '小赵'}，{label: '小强'}]</span>
<span class="token comment">//     },</span>
<span class="token comment">//     {</span>
<span class="token comment">//       label: '老李',</span>
<span class="token comment">//       children: [{label: '小涛'}]</span>
<span class="token comment">//     }</span>
<span class="token comment">//   ]</span>
<span class="token comment">// }]</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


